// import type { Metadata } from 'next'
// import './globals.css'

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode
// }>) {
//   return (
//     <html lang='en'>
//       <body className={``}>{children}</body>
//     </html>
//   )
// }

// app/layout.tsx
import HeadElement from '@/components/layout/HeadElement'
import Providers from '@/components/layout/Providers'
import '@/styles/globals.css'
import '@/styles/backgrounds.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Shalom Mission Church',
  description: 'Your App Description',
  icons: {
    icon: '/assets/brand/logo.png',
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={``}>
        <Providers>
          <HeadElement />
          {children}
        </Providers>
      </body>
    </html>
  )
}
